modLoader="javafml"
loaderVersion="[34,)"
license="MIT"

[[mods]]
modId="mycelia"
version="0.1"
displayName="Mycelia"
authors="Mortimyrrh"
description='''
This mod adds a new dimension for travelling around quickly, inspired by Star Trek Discovery.'''
logoFile="logo.png"
displayURL="http://github.com/Mortimyrrh/Mycelia"

[[dependencies.mycelia]]
modId="forge"
mandatory=true
versionRange="[34.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.mycelia]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"